### ISSUE TITLE
[Improvment Idea] Height configuration

### ISSUE THREAD

**Issue by Mokette** [egeinanc/dragonball-progressbar#18] opened 2022-12-12 14:35 UTC
Hello ,
Great work on this progress bar plugin dragon ball svg :)
Do you think it'll be possible to add configuration to set à min/max height of the progress bar ?
Because now it's really big and sometimes cause lag because force intellij to resize toolbar for the progress bar to fit it.

Regards

**Comment by egeinanc** [comment] 2022-12-12 15:33
I'll give it a try :)

Thank you for the improvement idea :)

**Comment by Mokette** [comment] 2023-03-31 14:54
Any update on this possible improvment ? :)
Regards

**Comment by egeinanc** [comment] 2023-04-01 08:28
> Any update on this possible improvment ? :) Regards

I didn't find the time yet. Thanks for the reminder. I will increase the priority of this :)

**Comment by egeinanc** [comment] 2023-04-10 14:12
Hey @Mokette,

i have started this feature. it's not quite done yet. you can find a current state in this PR: https://github.com/egeinanc/dragonball-progressbar/pull/25

**Comment by Mokette** [comment] 2023-04-13 08:16
Oh nice you've done some nice advancement for it :)
Well done for your scale function to resize icon regarding configurate height so theicon won't be strange stretch :)

**Comment by egeinanc** [comment] 2023-06-15 06:03
Hi @Mokette,
Sorry for the delay. I'm still sitting on it. The problem is that the animation do not playback as expected. As well as when running tests for example the animation does not run at all.
Scaling does work quite well with static images.

I am thinking about changing the whole set of graphics to only images. Do you have an opinion on that?

**Comment by Mokette** [comment] 2023-06-26 12:15
Hello @egeinanc ,
sorry gfor the late delay to answer.
i'm not surprise that scaling animation cause so much trouble.
Animation were cool but i think only use image for allowing proper scalling will be a better solution to keep intelliJ workplace works better without beeing resize if an image or animation is too height.

**Comment by Mokette** [comment] 2023-07-25 09:03
Hello @egeinanc 
any update on this ? :)

regards

**Comment by Mokette** [comment] 2023-07-25 12:24
Alright no problem ! 
yes i think non animated sprites will be a better solution to avoid blinking height and do a proper resizing :)
Enjoy your vacation

**Comment by egeinanc** [comment] 2023-08-16 05:56
@Mokette 
I have uploaded a new version. Therefore I would close this issue. There are not many sprites yet. But in the future i will create some.

I m looking forward to your feedback :)

**Closed** 2023-08-16 05:57 UTC

**Comment by Mokette** [comment] 2023-08-17 14:03
Hello @egeinanc 
thanks for your update, i've been try it since yesterrday, works well with the fix height, no resize of idea workspace
but i've notice an error for the resizing of the sprites, they don't fit in the progress bar
![Annotation 2023-08-17 154036](https://github.com/egeinanc/dragonball-progressbar/assets/9215212/4216506e-4bcd-4074-8944-6ccaf46de299)

sprite are less high thant the progress bar so on small size (currently 20px for me to fit my workspace size, the sprite is quite so small regarding the progress bar.

Hope you'll find a way to fix it.

Regards

**Comment by egeinanc** [comment] 2023-08-18 06:36
Hi @Mokette,

that's odd I cannot reproduce that issue somehow in the first sight.

I will dig deeper to find the problem.

<img width="263" alt="Bildschirmfoto 2023-08-18 um 08 34 13" src="https://github.com/egeinanc/dragonball-progressbar/assets/27723786/50d29e64-7cb2-43db-949c-c03a891179c6">

**Comment by egeinanc** [comment] 2023-08-21 11:27
Hi @Mokette ,

I uploaded a fix. You should have an update. If you have time then you could check if you still have that issue :)

**Comment by Mokette** [comment] 2023-08-22 09:11
Hi @egeinanc 
just downoad it, it works really well now ! thanks a lot for your time to develop this improvment
